### ISSUE TITLE
Issues in some example-normalized.json files

### ISSUE THREAD

**Issue by dpatil-fw** [smart-data-models/SmartCities#1]
Based on this doc: 
https://docs.google.com/presentation/d/e/2PACX-1vTs-Ng5dIAwkg91oTTUdt8ua7woBXhPnwavZ0FxgR8BsAI_Ek3C5q97Nd94HS8KhP-r_quD4H0fgyt3/pub?slide=id.gcc1dca0563_0_50

Submission of data model requires submitting 4 example files under examples dir.
While example.json is a simple key-value pair example, I have confusion over example-normalized.json

This example: https://github.com/smart-data-models/dataModel.PointOfInterest/blob/master/PointOfInterest/examples/example-normalized.json
has source and location represented as below:

```
  "source": {
    "value": "http://www.tourspain.es"
  },
  "location": {
    "type": "geo:json",
    "value": {
      "type": "Point",
      "coordinates": [-8.768460000000001, 42.60214472222222]
    }
  }  
```

However, this example: https://github.com/smart-data-models/dataModel.PointOfInterest/blob/master/Store/examples/example-normalized.json
has source and location represented differently.

source has a defined type as "Text" and location has a type "GeoProperty" instead of "geo:json"
 ```
 "source": {
    "type": "Text",
    "value": "https://api.smartsantander.eu/"
  },
  "location": {
    "type": "GeoProperty",
    "value": {
      "type": "Point",
      "coordinates": [
        -3.8077562,
        43.4628255
      ]
    }
  },
  "currenciesAccepted": {
    "type": "StructuredValue",
    "value": [
      "EUR"
    ]
  },

```
Also there is a "StructuredValue" defined above. 
This is present only in a few example-normalized.json under https://github.com/smart-data-models/SmartCities

- https://github.com/smart-data-models/dataModel.PointOfInterest/blob/master/Store/examples/example-normalized.json
- https://github.com/smart-data-models/dataModel.UrbanMobility/blob/master/PublicTransportRoute/examples/example-normalized.json
- https://github.com/smart-data-models/dataModel.UrbanMobility/blob/master/PublicTransportStop/examples/example-normalized.json

I have a few questions, 

* What exactly does a normalized json mean? Is it just an expanded format with type defined explicitly?
* If a tool like this exists: https://github.com/FIWARE/data-models/blob/master/tools/keyValues2Normalized.py that can generate a normalized json automatically from a key-value pair json,  is there a need to manually submit a normalized json?

**Comment by albertoabellagarcia** [comment]
Regarding PointOfInterest, you were right, examples were wrongly named (and some minor errors were present). Already fixed.
Thanks again :-D.
Normalized format is one of the formats that NGSI context broker returns on request, the other is the key values, but this format is slightly different from NGSIv2 to NSI-LDm, that's why there are four examples. 
The 4 examples are required for an accepted data model together with the schema
thanks
